CREATE OR ALTER PROCEDURE selectCharge(
@ID int
)
AS
BEGIN
	--NOT DOING ANY DATA VALIDATION BECAUSE THIS IS ONLY GOING TO BE CALLED INTERNALLY IN OUR UI CODE
	SELECT * 
	FROM [Charge]
	WHERE ID = @ID
END